export const products = [
    {
      id: 1,
      name: "Organic Rice Seeds",
      price: 499,
      imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRHBJhE-YsIrQfxLepgRNrfFPPxdB_J5Fs_KidQ-S8wRAOexktgqx8Ber4h9I_fP04OCi-QLsWtcL_XKdaW5Ltt81gLlu8VstngXK7_RCMH3LEeUA2_Weug",
      productUrl: "https://example.com/products/organic-rice-seeds",
      category: "Seeds",
    },
    {
      id: 2,
      name: "Natural Fertilizers",
      price: 499,
      imageUrl: "https://rukminim2.flixcart.com/image/850/1000/xif0q/soil-manure/9/w/q/1-100-blackpearl-organic-fertilizer-1kg-pack-1-original-imagg6k4yyavpzmb.jpeg?q=90&crop=false",
      productUrl: "https://example.com/products/natural-fertilizers",
      category: "Fertilizers",
    },
    {
      id: 3,
      name: "Farming Tools Set",
      price: 499,
      imageUrl: "https://m.media-amazon.com/images/I/91LqW7Ni4wL._AC_UF350,350_QL80_.jpg",
      productUrl: "https://example.com/products/farming-tools",
      category: "Equipment",
    },
    {
      id: 4,
      name: "Organic Pesticides",
      price: 499,
      imageUrl: "https://organicbazar.net/cdn/shop/products/Neem-Oil-for-Pests-Contro.jpg?v=1694167803",
      productUrl: "https://example.com/products/organic-pesticides",
      category: "Pesticides",
    },
    {
      id: 5,
      name: "Soil Testing Kit",
      price: 499,
      imageUrl: "https://m.media-amazon.com/images/I/713+nS5M8EL.jpg",
      productUrl: "https://example.com/products/soil-testing-kit",
      category: "Tools",
    },
    {
      id: 6,
      name: "Irrigation Supplies",
      price: 499,
      imageUrl: "https://m.media-amazon.com/images/I/81Uu5rxlFuL._AC_UF1000,1000_QL80_.jpg",
      productUrl: "https://example.com/products/irrigation-supplies",
      category: "Equipment",
    },
    {
        id: 7,
        name: "Farming Tools Set",
        price: 499,
        imageUrl: "https://m.media-amazon.com/images/I/719DGuug67L._AC_UF1000,1000_QL80_.jpg",
        productUrl: "https://example.com/products/farming-tools",
        category: "Equipment",
      },
  ];

  